#!/bin/sh

echo "---> Configuring tomcat manager auth..."
envtpl /opt/tomcat/conf/tomcat-users.xml.tpl --allow-missing

echo "---> Configuring server.xml...."
envtpl /opt/tomcat/conf/server.xml.tpl --allow-missing

echo "---> Configuring circus environment vars..."
envtpl /etc/circus.d/tomcat.ini.tpl --allow-missing

echo "---> chown tomcat /opt/tomcat ..."
chown tomcat.tomcat /opt/tomcat -R
echo done.
